
included:
  - {{cookiecutter.app_name}}
excluded:
  - Pods
  - {{cookiecutter.app_name}}/Other/R.generated.swift  


disabled_rules:
  - trailing_whitespace
  - legacy_constructor
  - void_return
  - cyclomatic_complexity
  - fallthrough
  - empty_enum_arguments
  - unused_optional_binding
  - multiple_closures_with_trailing_closure
  
file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*?\.swift
                    \/\/  {{cookiecutter.app_name}}
                    \/\/
                    \/\/  Created by .*? on \d{1,2}\/\d{1,2}\/\d{2}\.
                    \/\/  Copyright © \d{4} PixelPlex\. All rights reserved\.
                    \/\/
identifier_name:
  excluded:
    - id

line_length: 
  warning: 150

file_length: 
  warning: 750
  error: 1000

type_body_lenght:
  warning: 400
  error: 450

large_tuple: 10

function_body_length: 
  warning: 56
  error: 65

function_parameter_count:
  warning: 10
  error: 15
